# Generated by Django 3.0.3 on 2020-12-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOBILE_NUMBER', models.CharField(max_length=12)),
                ('FIRST_NAME', models.CharField(max_length=30)),
                ('LAST_NAME', models.CharField(max_length=30)),
                ('ID_TYPE', models.CharField(choices=[('1', 'Work ID'), ('2', 'Student ID')], max_length=10)),
                ('ID_NUMBER', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'CUSTOMER',
                'verbose_name_plural': 'CUSTOMERS',
            },
        ),
    ]
